name: 'Upload Episode from YouTube To Anchor.Fm'
description: 'An automation tool to publish your podcast from youtube to anchor.fm'
branding:
  icon: 'upload-cloud'  
  color: 'green'
runs:
  using: "docker"
  image: "Dockerfile"
on:
  push:
    paths:
      - episode.json
    branches: [master]
jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Anchor.Fm
        uses: arumugam6/youtube-to-anchorfm@v0.1.5
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
env:
  ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
  ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
